// src/app/api/nft/ipfs-upload/route.ts
import { NextResponse } from 'next/server';
import { DB } from '@/lib/db';
import { kv } from '@vercel/kv';
import { uploadFileToPinata, uploadJsonToPinata, getPinataUrl } from '@/lib/pinata';

// Функция для получения следующего номера NFT
async function getNextNftNumber(): Promise<number> {
  // Получаем текущий счетчик
  const currentCount = await kv.get('nft:counter') as number || 0;
  
  // Увеличиваем счетчик
  const nextCount = currentCount + 1;
  
  // Сохраняем новое значение
  await kv.set('nft:counter', nextCount);
  
  return nextCount;
}

export async function POST(request: Request) {
  try {
    const { wallet } = await request.json();
    
    if (!wallet) {
      return NextResponse.json({ error: 'Wallet address is required' }, { status: 400 });
    }
    
    // Получаем заявку
    const application = await DB.getApplicationByWallet(wallet);
    if (!application) {
      return NextResponse.json({ error: 'Application not found' }, { status: 404 });
    }
    
    // Проверяем, что заявка находится в статусе nft_approved
    if (application.status !== 'nft_approved') {
      return NextResponse.json({ 
        error: `NFT not approved for minting, current status: ${application.status}` 
      }, { status: 400 });
    }
    
    // Проверяем, не загружено ли уже в IPFS
    const existingIpfs = await kv.hget(`application:${application.id}`, 'ipfsImage');
    if (existingIpfs) {
      const ipfsMetadata = await kv.hget(`application:${application.id}`, 'ipfsMetadata');
      const nftNumber = await kv.hget(`application:${application.id}`, 'nftNumber');
      
      return NextResponse.json({ 
        success: true, 
        message: 'Already uploaded to IPFS',
        ipfsImage: existingIpfs,
        ipfsMetadata,
        nftNumber,
        ipfsImageUrl: getPinataUrl(existingIpfs as string),
        ipfsMetadataUrl: ipfsMetadata ? getPinataUrl(ipfsMetadata as string) : null
      });
    }
    
    // Получаем URL изображения
    if (!application.imageUrl) {
      return NextResponse.json({ error: 'No image URL found for this application' }, { status: 400 });
    }
    
    // Загружаем изображение по URL
    const imageResponse = await fetch(application.imageUrl);
    if (!imageResponse.ok) {
      return NextResponse.json({ 
        error: `Failed to fetch image from URL: ${imageResponse.statusText}` 
      }, { status: 500 });
    }
    
    // Получаем бинарные данные изображения
    const imageBuffer = Buffer.from(await imageResponse.arrayBuffer());
    
    // Получаем метаданные
    const metadataStr = await kv.hget(`application:${application.id}`, 'metadata');
    if (!metadataStr) {
      return NextResponse.json({ error: 'No metadata found for this application' }, { status: 400 });
    }
    
    // Парсим метаданные
    let metadata;
    try {
      metadata = typeof metadataStr === 'string' ? JSON.parse(metadataStr) : metadataStr;
    } catch (error) {
      return NextResponse.json({ 
        error: 'Failed to parse metadata JSON' 
      }, { status: 500 });
    }
    
    // Получаем следующий номер NFT
    const nftNumber = await getNextNftNumber();
    
    // Загружаем изображение в IPFS
    const imageFileName = `dewild-${nftNumber}.png`;
    const imageDescription = `DeWild NFT #${nftNumber} by @${metadata.artist}`;
    
    console.log('Uploading image to IPFS...');
    const imageIpfsHash = await uploadFileToPinata(
      imageBuffer,
      imageFileName,
      { description: imageDescription }
    );
    console.log('Image uploaded to IPFS, hash:', imageIpfsHash);
    
    // Формируем метаданные NFT в формате ERC721
    const nftMetadata = {
      name: `DeWild #${nftNumber}`,
      description: metadata.description || metadata.statement || `DeWild NFT generated by @${metadata.artist}`,
      image: `ipfs://${imageIpfsHash}`,
      external_url: `https://dewild.art/nft/${nftNumber}`,
      attributes: [
        {
          trait_type: "Animal",
          value: metadata.traits?.animal || "Unknown"
        },
        {
          trait_type: "Material",
          value: metadata.traits?.material || "Unknown"
        },
        {
          trait_type: "Material Color",
          value: metadata.traits?.material_color || "Unknown"
        },
        {
          trait_type: "Background",
          value: metadata.traits?.background || "Unknown"
        },
        {
          trait_type: "Pattern Color",
          value: metadata.traits?.pattern_color || "Unknown"
        },
        {
          trait_type: "Eyes Color",
          value: metadata.traits?.eyes_color || "Unknown"
        },
        {
          trait_type: "Artist",
          value: metadata.artist || "Unknown"
        },
        {
          trait_type: "Statement",
          value: metadata.statement || "None"
        }
      ]
    };
    
    // Загружаем метаданные в IPFS
    console.log('Uploading metadata to IPFS...');
    const metadataFileName = `dewild-${nftNumber}.json`;
    const metadataIpfsHash = await uploadJsonToPinata(
      nftMetadata,
      metadataFileName
    );
    console.log('Metadata uploaded to IPFS, hash:', metadataIpfsHash);
    
    // Сохраняем IPFS хэши в KV-хранилище для заявки
    await kv.hset(`application:${application.id}`, {
      ipfsImage: imageIpfsHash,
      ipfsMetadata: metadataIpfsHash,
      nftNumber: nftNumber,
      ipfsTimestamp: Date.now()
    });
    
    // Сохраняем информацию о токене для доступа через метаданные API
    await kv.hset(`nft:${nftNumber}`, {
      ipfsImage: imageIpfsHash,
      ipfsMetadata: metadataIpfsHash,
      applicationId: application.id,
      wallet: wallet,
      artist: metadata.artist || "",
      statement: metadata.statement || "",
      animal: metadata.traits?.animal || "Unknown",
      material: metadata.traits?.material || "Unknown",
      material_color: metadata.traits?.material_color || "Unknown",
      background: metadata.traits?.background || "Unknown",
      pattern_color: metadata.traits?.pattern_color || "Unknown",
      eyes_color: metadata.traits?.eyes_color || "Unknown",
      timestamp: Date.now()
    });
    
    // Проверяем, нужно ли обновить baseURI в контракте (для первого NFT)
    if (nftNumber === 1) {
      // Сохраняем информацию о первом NFT для последующей установки baseURI
      await kv.set('nft:firstMetadata', {
        nftNumber,
        ipfsHash: metadataIpfsHash,
        timestamp: Date.now()
      });
      
      console.log('First NFT uploaded to IPFS. You should update the baseURI in your contract.');
    }
    
    return NextResponse.json({ 
      success: true, 
      ipfsImage: imageIpfsHash,
      ipfsMetadata: metadataIpfsHash,
      nftNumber: nftNumber,
      ipfsImageUrl: getPinataUrl(imageIpfsHash),
      ipfsMetadataUrl: getPinataUrl(metadataIpfsHash),
      isFirstNft: nftNumber === 1
    });
    
  } catch (error: any) {
    console.error('Error uploading to IPFS:', error);
    return NextResponse.json(
      { error: 'Failed to upload to IPFS', details: error?.message },
      { status: 500 }
    );
  }
}